# Generated by Django 5.1.3 on 2024-12-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='recepie-img/%Y/%m/%d/'),
        ),
    ]
