# Generated by Django 5.1.3 on 2024-12-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='recepie-img/%Y/%m/%d/'),
        ),
    ]
